// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "seu_login_name_aqui";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password


String horarioRega;
int nCiclos;
int umidade;
int temperatura;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(horarioRega, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(nCiclos, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(umidade, READ, 3600 * SECONDS, NULL);
  ArduinoCloud.addProperty(temperatura, READ, 3600 * SECONDS, NULL);
  

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
